### ISSUE TITLE
Add Integration Tests Section with Vuex

### ISSUE THREAD

**Issue by beeetooo** [lmiller1990/vue-testing-handbook#109]
## Description
I have struggled a lot with testing in Vue.js due to a big lack of documentation from the Vue main page. I have found multiple very useful resources and this is actually one of them.
I just want to see how can I help you integrate an `Integration Testing` section, as I see it as a very powerful test that adds TONS of value at the moment of a complete validation of a feature. Just to make sure we are in the same channel, I'm referring to an Integration Test not to the Selenium tests that opens the browser and starts to do interactions with the app, but as `a test that validates the functionality of a section of the application by running the complete flow of data and interactions`

Let me put a small example. Let's suppose we have a web page that has a list of Pokemons. In the page, we have a Container Component that fetches the pokemons from an API, and then renders the pokemons in the screen.

**containers/PokemonList.vue**
```vue
<template>
  <div class="pokemon">
    <template v-for="pokemon in pokemons">
      <p class="pokemon__name">{ pokemon.name }</p>
    </template>
  </div>
</template>

<script>
export default {
  computed: {
    ...mapState({
       pokemons: state => state.pokemons
     })
  },
  methods: {
    ...mapActions(['fetchPokemons'])
  },
  mounted: function () {
    // assuming this is an store action that will fetch the pokemons and 
    // putting them into the Vuex store.
    this.fetchPokemons() 
  }
}
</script>
```

```js
import { mount } from '@vue/test-utils'
import PokemonList from '@/containers/PokemonList.vue'

describe('Pokemon List', () => {
  it('should render the pokemon list', () => {
    axiosMocker
      .onGet('https://pokeapi.co/pokemons')
      .reply(200, [{ name: 'Pikachu' }, { name: 'Charmander' })

    const component = mount(PokemonList)
    
    await flushPromises() // wait for the action `fetchPokemons` to be executed

    const pokemons = component.findAll('.pokemon')
    expect(pokemons.length).toEqual(2)
    expect(pokemons.at(0).find('.pokemon__name')).toEqual('Pikachu')
    expect(pokemons.at(1).find('.pokemon__name')).toEqual('Charmander')
  })
})
```

Running that complete flow fits perfectly into an Integration test. I have had tons of struggles doing this kind of tests but it has been super satisfying to make them and I think your page should have a section for it. Let me know what you think!

Some of the resources I have found useful:
- https://vue-test-utils.vuejs.org/
- https://github.com/mcibique/vue-testing-examples

**Comment by lmiller1990** [comment]
Hi @beeetooo ,

This sounds like a good idea. We have all the parts of an integration test, as such, but a guide combining them all together would be a great addition.

If you want to start drafting something, just make a new page in the `src` directory and maybe add a brief outline. If we can stick to the stack the rest of the handbook uses (jest, axios) that would be great, too. 

Alternatively, pull down the repo, and write the tests you'd like to discuss in the `demo-app` and make sure they all pass. Then we can do the write up afterwards.

What do you think? :) I'm excited for this contribution!

**Comment by beeetooo** [comment]
Yes!! Sorry for not replying, I thought I did haha. Yes! Let me work on this one, it might be a bit delayed but I'll come up with a PR soon in the next two weeks I hope <3 excited about this too!

**Comment by beeetooo** [comment]
Still working on this one :+1:

**Comment by lmiller1990** [comment]
No problem, take your time
