### ISSUE TITLE
Vue Router > Component Guards > beforeRouteLeave doesnt call with "this"

### ISSUE THREAD

**Issue by thejcannon** [lmiller1990/vue-testing-handbook#113]
The `beforeRouteLeave` in-component guard [has access to `this`](https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards) but the example doesn't pass in a context.

The example should probably be updated to do something like:
```js
it("calls bustCache and next when leaving the route", () => {
  const wrapper = shallowMount(NestedRoute);
  const next = jest.fn()
  NestedRoute.beforeRouteLeave.call(wrapper.vm, undefined, undefined, next)

  expect(mockModule.bustCache).toHaveBeenCalled()
  expect(next).toHaveBeenCalled()
})
```

and probably add an info box about routes that can use `this`

**Comment by lmiller1990** [comment]
Hm, good point. Would you like to make a PR with this? If not, I am happy to do so.

**Comment by thejcannon** [comment]
I would love to, but unfortunately it'll be a while before I have the time. I'm happy to review it, however 😄
