### ISSUE TITLE
I have no way to contact you

### ISSUE THREAD

**Issue by kahirokunn** [lmiller1990/vue-testing-handbook#114]

**Comment by kahirokunn** [comment]
Hi 👋 
Long time no see you!
I mess you!
I’m drinking with @yk-hirao now.
I want to talk after a long time😆

**Comment by ykhirao** [comment]
i miss you ; (

**Comment by kahirokunn** [comment]
@lmiller1990 I miss you 😢

**Comment by lmiller1990** [comment]
message me on LINE!

![67585164_2620971481280619_2848879406896644096_n](https://user-images.githubusercontent.com/19196536/61915415-a11d2b80-af87-11e9-9c4e-895205214e27.jpg)

Find me!! I miss you guys too 👍 日本を出て日本語をほぼ使ってなくてまだ喋るのかな 🤔 

I want to visit Japan soon! React is too popular, I miss Vue. 👍

**Comment by kahirokunn** [comment]
Don’t worry!
I’m trying to learning English now!
Let’s talk by English 🤩

**Comment by ykhirao** [comment]
Thx :+1:
