### ISSUE TITLE
Translate vuex getters to Japanese

### ISSUE THREAD

**Issue by buntafujikawa** [lmiller1990/vue-testing-handbook#119]
@lmiller1990 
Hi! May I make a PR?
https://github.com/lmiller1990/vue-testing-handbook/blob/master/src/vuex-getters.md
https://github.com/lmiller1990/vue-testing-handbook/blob/master/src/ja/vuex-getters.md

**Comment by lmiller1990** [comment]
@buntafujikawa お願いします！
