### ISSUE TITLE
Bump versions

### ISSUE THREAD

**Issue by lmiller1990** [lmiller1990/vue-testing-handbook#121]
Should bump

- versions of Vuepress
- versions of vue, vue-test-utils etc in the demo app

**Comment by spencer1573** [comment]
getting this done now

**Comment by spencer1573** [comment]
i'm going to use the latest edge node - 12.12.0 let me know if you want the current latest LTS 10.16.3

**Comment by lmiller1990** [comment]
Hey, thanks! Let's go with LTS - I think that's more likely what people will be using in production.

**Comment by lmiller1990** [comment]
Will need to make sure you can `cd demo-app`, `yarn install` and `yarn test:unit` works fine as well 👍

**Comment by spencer1573** [comment]
complete. see pull request [#125](https://github.com/lmiller1990/vue-testing-handbook/pull/125)

**Comment by spencer1573** [comment]
oh crap i did 12.12.0 and i didn't test the demo-app. is it alright if I do that tomorrow?

**Comment by spencer1573** [comment]
doing it correctly right now...

**Comment by spencer1573** [comment]
ok everything is correct now! more details in the [pull request #126](https://github.com/lmiller1990/vue-testing-handbook/pull/126), all unit tests passed for demo app.
