### ISSUE TITLE
translate the guide to spanish language

### ISSUE THREAD

**Issue by kimagure44** [lmiller1990/vue-testing-handbook#127]
I would be interested in being able to translate your guide into the Spanish language

**Comment by lmiller1990** [comment]
Sure, if you like!

I'll be making a few changes this week for vue-test-utils beta 28 - maybe wait a few days before you get too deep.

**Comment by kimagure44** [comment]
ok, I look forward to when I can start doing the translation. Thank you very much and greetings

**Comment by lmiller1990** [comment]
Looks like everything is fine, even with `@vue/test-utils` version 29. You can start a translation if you like :)

**Comment by kimagure44** [comment]
Hi, I have a question, I have already started translating the guide, when I finish translating it, do I request a pull request?

**Comment by lmiller1990** [comment]
Ideally we will translate the entire book before merging it in - I understand this is a big task, but I'm not sure a partial translation is ideal.

**Comment by kimagure44** [comment]
Ok, when i finished the translate i request a PR.

Thank you very much and greetings

**Comment by enriqg9** [comment]
I can help translating into spanish as well. @kimagure44 have you made progress with this? @lmiller1990 Should we wait for Vue 3 compatible handbook?

**Comment by lmiller1990** [comment]
@enriqg9 probably a good idea to wait, I need to update some things for Vue 3.

**Comment by kimagure44** [comment]
Excuse me @lmiller1990 and @enriqg9 , but I've been with a new project since the end of the year and I haven't been able to advance the translation as fast as I would have liked. At the moment I have 30% translated into Spanish. When you have the new changes to Vue 3 continue with the translation

**Comment by lmiller1990** [comment]
Ok I will ping you then (sometime in May)

**Comment by LittaPanda** [comment]
Hi guys,
I'd love to help with this.
Just tell me what do you need.
If you guys have a progress list or something like this will be great.
Regards!

**Comment by shortpoet** [comment]
Same here.  Would be fun to do a collaboration project on this! :)

**Comment by lmiller1990** [comment]
While I don't have time to lead a translation (although I'm flattered people want to translate my content) here is what I think would work:

- someone will need to "lead" the project
- said person will fork this book
- he/she will make a GH issue for each article
- assign someone to each article
- merge the translated articles into the fork
- finally, when the book is complete, we merge it back here and release.

:D

**Comment by LittaPanda** [comment]
Hi!
I'll be pleased to “lead” the translation. 
Let me start doing the issues and then assign them.
I'll try to integrate the @kimagure44 job in order to do this faster.
Regards

**Comment by LittaPanda** [comment]
Hi guys,
Here is the project!
https://github.com/LittaPanda/vue-testing-handbook/projects/2
https://github.com/LittaPanda/vue-testing-handbook

I did created the issues/cards for every single file, so feel free to take as you want.
Regards

**Comment by enriqg9** [comment]
@LittaPanda Will try to start contributing in the next days. @lmiller1990 Do you expect a lot of the content changing due to update of Vue 3/VTU?

**Comment by LittaPanda** [comment]
@shortpoet 
Can I assign to you any issue?
Regards

**Comment by shortpoet** [comment]
@LittaPanda I had mentioned in a separate issue in the handbook that I was in the midst of writing unit tests for my site and would be able to contribute once that was done or close to.  I have 100% coverage on my javascript except for the router which I'm thinking of saving for integration.  Just doing the dotnet core tests now.  Have had to learn all this from scratch pretty much so not sure exactly when I will be able to shift my focus.  I'm hoping by mid-end week next at the latest.  I am excited to try to start using tools to automate translation tasks which I also mentioned in that issue.  Started looking at some python libraries for that.  What tools are you guys using?

**Comment by lmiller1990** [comment]
@enriqg9 I don't expect the content to change significantly. 

Some things like `createLocalVue` do not exist in Vue 3. Is the goal here to provide a translation for for the current book focused on Vue 2, or for the future (Vue 3?)

I still think there is some value in translating for Vue 2; we can likely use around 80% of the content for the Vue 3 edition, too.

Main changes in Vue 3:

- `createLocalVue` is gone (no more global Vue instance in Vue 3)
- some basic syntax (`propsData` -> `props`)
- `find` is now `find`  for DOM elements and `findComponent` for components

Full API is [here](https://vuejs.github.io/vue-test-utils-next-docs/api/).

At this point I would recommend translating the current content; Vue 2 will still be widely used for the next few years.

When I finish Vue 3 updates, we can likely reuse around 80% of the content and just tweak for Vue 3 :)

Thanks for this everyone! I'm honestly honored people translate my content. You are welcome to partial posts translations on your personal blogs, just leave a link back here somewhere :)

**Comment by enriqg9** [comment]
@lmiller1990 Awesome, we have started the translation for Vue 2 over at @LittaPanda's repo. Been tied up with a family emergency but will continue contributing when I have some spare time.

**Comment by lmiller1990** [comment]
No problem... it's OSS, live needs to come first :)

**Comment by vborras** [comment]
Hi @LittaPanda! I'm interested in contributing to the translation, but I see there hasn't been any changes in your repo for a while. Are you still working on it? If so, how do we proceed? do you want to assign some issue to me or can I take any one of them?

**Comment by LittaPanda** [comment]
Hi @vborras. Thanks for your interest. I would be glad if you could help us with this achievement.
I will assign you an issue right now.
Again thanks.

**Comment by lmiller1990** [comment]
Close due to lack of activity. Can reopen if progress starts up again.
