### ISSUE TITLE
Translate: I wish to translate this guide into Korean.

### ISSUE THREAD

**Issue by Junkim93** [lmiller1990/vue-testing-handbook#129]
Hello,

Thanks to your posting, I got help with vue testing.

So, I would be interested to translate your handbook into the Korean language.

**Comment by lmiller1990** [comment]
Hey @Junkim93 ,

Sure, that's no problem. I prefer to have a complete translation before merging - feel free to open a PR as you work on it. Ideally we will merge after the entire translation is complete.

You are also welcome to post your translations on other blogs or websites as you go :) thanks for your interest in this project!

**Comment by Junkim93** [comment]
Got it.
I post on my blog after translation to each chapter.
Then, I will open to PR when I translate all of it.

Thank you for your concern.

**Comment by lmiller1990** [comment]
Great. Can you share a link to your blog here, as well? Thanks!

**Comment by Junkim93** [comment]
Sorry for the late reply.
My blog is below.
https://junkim.netlify.com/posts/testingvue01

Thank you!

**Comment by lmiller1990** [comment]
Nice job, I'm so excited to see a Korean translation in progress.  감사합니다 !

**Comment by Junkim93** [comment]
Hello @lmiller1990 

I will share my progress on Korean translation version.
It was left last 3 articles:
- Vue Router
- Composition API
- Jest-mocking modules

It will expect to finish in the between 2nd and 3rd week of this month, since I need to time for checking my translation.

Too interesting your upcoming course
and happy new year 2020.

**Comment by lmiller1990** [comment]
Wow, awesome progress!! Unfortunately Jest-mocking modules does not have an English version yet... I should write that soon.

I'll be give you early access to my course when I have recorded it (still waiting on Vue.js 3 so I can record it, haha). Happy new year to you too!

**Comment by lmiller1990** [comment]
Merged!
