### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by tonylua** [lmiller1990/vue-testing-handbook#133]
hi, Lachlan!

Thanks for your series of articles that have helped me better understand unit tests in vue.js. I have also tried to translate some of them into Chinese and shared them with more Chinese developers. 

Here are some links:

- [Unit Testing the Composition API](https://mp.weixin.qq.com/s/VcyoX3bYLHSBkQD3YW8i4w)
- [Mocking Vue.js global objects in vue-test-utils](https://mp.weixin.qq.com/s/MLmt3yWtOxRVTW_92eMwJQ)
- [Unit Testing Vue-Router](https://mp.weixin.qq.com/s/0p51k6wF0C-UT_8kQ6Iiqw)

I would like to translate the more complete "vue-testing-handbook" into Chinese. I hope I can have this opportunity. Thank you~

**Comment by Blackgan3** [comment]
We can do it together

**Comment by lmiller1990** [comment]
Hi guys. I prefer to merge when we have a full translation, as opposed to article by article - if that's okay, and you are still interested in doing that, go for it!

Also one problem I'm having is translations get out of date to the "source" (English one) pretty fast. Does anyone have any good solutions for this problem?

**Comment by tonylua** [comment]
Ok, thanks for the support! I'll talk to @Blackgan3 about how we can work together，and merge as much as possible at once.

**Comment by tonylua** [comment]
> We can do it together

send me a wechat plz.

**Comment by lmiller1990** [comment]
Feel free to collaboration here too - open collaboration is the best kind 👍

**Comment by tonylua** [comment]
Hi, guys

I have done the preliminary work - have folked a [repository](https://github.com/tonylua/vue-testing-handbook) , and have updated the translations of the three articles mentioned earlier

- [composition-api](https://github.com/tonylua/vue-testing-handbook/commit/a25b48ce86be389699102685491b3e0910185dc4)
- [vue-router](https://github.com/tonylua/vue-testing-handbook/commit/9d8e456c653b2ccc3cc3a0a9fb1891a1f075f26c)
- [mocking-global-objects](https://github.com/tonylua/vue-testing-handbook/blob/master/src/zh-CN/mocking-global-objects.md)

In the next step, I will gradually complete the whole translation work. If Blackgan3 or someone else wants to join (or help with the review), please feel free to contact me

**Comment by tonylua** [comment]
@lmiller1990 the MR is ok，plz check it again :p

**Comment by lmiller1990** [comment]
Hey @tonylua / @Blackgan3 

Excellent work. I have merged your translation, should live now! Thanks a lot ❤️ 🇨🇳

**Comment by tonylua** [comment]
@lmiller1990  Thank you for your support & Happy New Year 😄

**Comment by tonylua** [comment]
and thank my friend @davidkoree for helping to review some articles!

**Comment by tonylua** [comment]
Congratulations you on being maintainer of the vue-test-utils project! @lmiller1990

**Comment by lmiller1990** [comment]
Oh, thanks @tonylua . I'm excited to be maintaining a project I've spent so long writing about :)
