### ISSUE TITLE
翻訳: コンポーネントをスタブガイド

### ISSUE THREAD

**Issue by lmiller1990** [lmiller1990/vue-testing-handbook#15]
英語→日本語

https://github.com/lmiller1990/vue-testing-handbook/blob/master/src/stubbing-components.md

**Comment by lmiller1990** [comment]
@Fanyu7 Yes please!!

**Comment by Fanyu7** [comment]
@lmiller1990  OK! :D

**Comment by lmiller1990** [comment]
You are #2 contributor!

![image](https://user-images.githubusercontent.com/19196536/43556667-eb202400-963b-11e8-96f0-f08c4835c509.png)
