### ISSUE TITLE
Why is there no ChildComponent spec?

### ISSUE THREAD

**Issue by geoidesic** [lmiller1990/vue-testing-handbook#152]
Hi,
I notice that there is a ParentComponent spec, but not one for the child? Isn't it useful for the child to be tested independently of the parent? I would expect so.

But then what if the child is dependent on the parent?

**Comment by lmiller1990** [comment]
Can you give me an example of what you'd like to see tested?

**Comment by geoidesic** [comment]
My apologies. Not a well-written issue and looking back at it not even I'm sure what I was asking for. Clearly I didn't understand something. I'll circle back if it comes up again.
