### ISSUE TITLE
Default mocks using deprecated syntax?

### ISSUE THREAD

**Issue by 3nuc** [lmiller1990/vue-testing-handbook#154]
https://lmiller1990.github.io/vue-testing-handbook/mocking-global-objects.html#settings-default-mocks-using-config

It says to import default and set the config on that, but i've found that doesn't work. The vue test utils docs say to import {config} now and that worked for me. https://vue-test-utils.vuejs.org/api/config.html

The default export didn't work for me but it seems weird that I can't do vuetestutils.config["global"]. Can anybody else confirm this no longer works?

Wanted to submit issue because this vue testing handbook result is the first result in google for mocking vue instance properties globally.

**Comment by lmiller1990** [comment]
I will check this out now.

**Comment by lmiller1990** [comment]
Ok you are right - we changed the API (after beta 29 I guess). 

I updated it! Thanks a lot!
