### ISSUE TITLE
The information about testing Vuex getters is wrong

### ISSUE THREAD

**Issue by geoidesic** [lmiller1990/vue-testing-handbook#172]
Firstly the link to GitHub at the bottom of this page is broken: https://lmiller1990.github.io/vue-testing-handbook/vuex-getters.html#testing-getters

Secondly this guide recommends that one should manually pass in state to the getters and that they are "just ordinary functions". But this isn't true: 
A) Getters are used directly as values, not called as functions and 
B) these examples do not deal with the other arguments that can be used within a getter, e.g. `getters`, `rootState`, `rootGetters`.

As an example of both where the described style of testing will not work...
I have getters like this:
```
export function isFlaggedOnline(state, getters) {
  return getters.networkOnline && getters.enabled;
}
export function networkOnline(state) {
  return state.networkOnline === true ? true : false;
}
export function enabled(state) {
  return state.enabled === true ? true : false;
}
```
But with tests like this:
```
import * as getters from 'src/store/online/getters`
it("isFlaggedOnline default state: offline", () => {
    expect(getters.isFlaggedOnline(state, getters)).toBe(false);
  });
```
I get errors:
```
Error: expect(received).toBe(expected) // Object.is equality
Expected: false
Received: [Function networkOnline]
```
Even though in the actual component the `isFlaggedOnline` getter is working. If I rewrite the getter like this:
```
export function isFlaggedOnline(state, getters) {
  return getters.networkOnline(state, getters) && getters.enabled(state, getters)
}
```
Then the test passes, but the actual component raises errors:
```
TypeError: getters.networkOnline is not a function
```
Catch 22

**Comment by geoidesic** [comment]
Is this a bug in `vue-test-utils`?
Or is there a correct way to handle this that can be added to the documentation here?

**Comment by lmiller1990** [comment]
Hi!

I should probably update this section of the book, I wrote it many years ago at this point. You are correct in saying that if you are using the second argument which is other getters, this strategy will *not* work.

I will have a think about how to handle, please wait a bit.

**Comment by lmiller1990** [comment]
I am going to rewrite the Vuex section soon. I will close this. Let me know if you have any other questions.
