### ISSUE TITLE
How does bustCache work?

### ISSUE THREAD

**Issue by ismatech** [lmiller1990/vue-testing-handbook#173]
Hi!
This is more of a question than an issue.
I am learning JEST testing of Vue components on your site.
And when I reached topic about Router you showed some bust-сache.js which just export function bustCache with empty body.
Did you do that just for a demonstration of some script which could do some functionality?
Or it really works? And my main question is If it so then how does it work?

**Comment by lmiller1990** [comment]
This was just an example for a strategy to test a router guard. Bust cache does not actually exist in the example. Is that what you mean?

**Comment by ismatech** [comment]
> 
> 
> This was just an example for a strategy to test a router guard. Bust cache does not actually exist in the example. Is that what you mean?

Yes, it's what I meant. Thanks.
