### ISSUE TITLE
Translate guide to Bahasa 

### ISSUE THREAD

**Issue by huntz20** [lmiller1990/vue-testing-handbook#174]
Hei can i support this awesome guide to bahasa ??

**Comment by lmiller1990** [comment]
Sure, I don't generally want to merge incomplete translations, though. An alternative would be translate articles 1 by 1 and post it to your own blog. When you finish the full translation, we could merge it.

**Comment by lmiller1990** [comment]
Close due to lack of activity. Will reopen if something changes.
