### ISSUE TITLE
Typo in v3/stubbing-components.md

### ISSUE THREAD

**Issue by Thomasan1999** [lmiller1990/vue-testing-handbook#190]
In **Write a test using `mount`** section, there is a sentence:

> findComponent is used when looking for a specific component, a takes a component as the argument.

I'm sure "a takes a component" is not correct but I'm not sure what to replace it with. Should it have been "and takes a component"?

**Comment by webistomin** [comment]
> In **Write a test using `mount`** section, there is a sentence:
> 
> > findComponent is used when looking for a specific component, a takes a component as the argument.
> 
> I'm sure "a takes a component" is not correct but I'm not sure what to replace it with. Should it have been "and takes a component"?

I think it should have been "it takes a component as the argument"

**Comment by Thomasan1999** [comment]
I see. Should I make a PR or leave it up to you?

**Comment by webistomin** [comment]
You can push one more commit to your PR.
