### ISSUE TITLE
jest.init.js does not load before test runs by default

### ISSUE THREAD

**Issue by sethPoulin** [lmiller1990/vue-testing-handbook#195]
In the chapter `mocking-global-objects.md`,  it's suggested to add the mock for the i18n library to the `jest.init.js` file, since this file "is loaded before the tests are run automatically."  But this needs to be expressly configured by adding the following to the `jest.config.js` file:

```js
export default {
    setupFiles: ["<rootDir>/jest.init.js"]
}
```
I'd suggest you add this to the documentation or suggest that users of the testing guide copy the `jest.config.js` file from the repo.

Thanks for putting this guide together!

**Comment by lmiller1990** [comment]
Good idea, I'd like to add this. Thanks for pointing this out!

**Comment by sethPoulin** [comment]
Sure, I'd be happy to.
