### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by Yan-Thomas** [lmiller1990/vue-testing-handbook#196]
First and foremost, thanks for this amazing guide on how to test Vue.js components!

I have seen there was a previous attempt at translating this guide to pt-BR (see #122), but looks like it was unfortunately abandoned. 

As a matter of context, I'm currently teaching Vue.js to some students at my school, so translating this would be a perfect opportunity to lend them a great material on component testing for free and with less effort than making something myself from zero.

I started working on it [here](https://github.com/Yan-Thomas/vue-testing-handbook). Anyone, please feel free to contribute. Doesn't matter if it's a mere fix or an entire page translation.

Note: Sorry, I didn't knew if I should open a new issue or instead restart the conversation on the old one, I'm not very knowledgeable about the workflow on open-source projects yet.

**Comment by lmiller1990** [comment]
Cool, thanks for the effort. Happy to have translations, but only if they are complete (eg, not looking to accept a PR translating half the content).

**Comment by ecanquiz** [comment]
Hi Lachlan Miller!!

You can count on me to translate all of that into Spanish. I have already translated many things that have to do with Vue (TDD), Jest, Vitest, VTU, VTL, VueCypress, VueRouter, Vuex, Pinia, etc. Even stuff from you like the Vue Testing Handbook and your Vue Testing Library videos Simple and Complete Tests. But using Vitepress...

Whenever you like we can talk about it.

Greetings !!

**Comment by lmiller1990** [comment]
I'd recommend just posting your translation on your own GitHub pages. I can link to it, if you like, from the main English version.

**Comment by ecanquiz** [comment]
Ok, ok, right now I have this page made by me:

https://caribestic.github.io/vue-tdd/

Please review it a bit (your opinion means a lot to me). There are many TDD things, yours and others.

Warning: But, I think I'm going to change the domain, because I'm trying to grow my own personal brand. In the future it would be something like "ecanquiz.github.io/vue-tdd". But beware: I have not changed it yet...

I would like to keep in touch with you to let you know if there are any changes in this regard and to be aware of your valuable contributions.

Thank you !!

**Comment by lmiller1990** [comment]
I am not sure I have time to review, but if you want to use my stuff, that's fine, just link back to the original where appropriate!

**Comment by ecanquiz** [comment]
Okay I understand.

Already confirmed, the new route is:
https://ecanquiz.github.io/vue-tdd/

I try (and will try) as much as possible to mention the original sources. In this case, you.

For example on this page (at the beginning) I make a mention saying **"Prueba, Esta lección en video"** _(Test, This video lesson)_ and I link it to your video:
https://ecanquiz.github.io/vue-tdd/vtl/psyc/consultas-dom.html

Yes I would like to follow you as much as I can to see when you make updates and release new things about it. I understand you're with Cypress now, great. Greetings...
