### ISSUE TITLE
testing an Emitted Events

### ISSUE THREAD

**Issue by ehsan-shv** [lmiller1990/vue-testing-handbook#198]
In a situation that we want to test just emitting event to parent, what can we  do?
For example, we have an event emitter like this:  `emit('onInputButtonClick');` and this event emitter just emits an event to the parent without sending any data.

**Comment by lmiller1990** [comment]
Assert that `emitted()` contains the expected property, in this case `expect(wrapper.emitted().onInputButtonClick).toHaveLength(1)`.
