### ISSUE TITLE
翻訳: コンポーネントをレンダーガイド

### ISSUE THREAD

**Issue by lmiller1990** [lmiller1990/vue-testing-handbook#2]
English -> Japanese

https://github.com/lmiller1990/vue-testing-handbook/blob/master/src/rendering-a-component.md

**Comment by Fanyu7** [comment]
@lmiller1990  私やってみます。アサインお願いします

**Comment by lmiller1990** [comment]
Thanks!

**Comment by yk-hirao** [comment]
@lmiller1990 `self-assigned` w

**Comment by lmiller1990** [comment]
間違った

@Fanyu7  にアサインする
