### ISSUE TITLE
New sections?

### ISSUE THREAD

**Issue by lmiller1990** [lmiller1990/vue-testing-handbook#39]
Some sections of Vue testing are not yet covered.

1. Vue router
2. functional components?
3. plugins?
4. snapshot testing?

Any ideas for new sections can be discussed here!

**Comment by yk-hirao** [comment]
How about testing DOM change like `document.qeurySelector`.
This test use just jest function, not Vue-test-utils.

But I think a lot of people use jQuery (or `querySelector`) on Vue.js, so this is a valuable section.

ないよりはあったほうがいいかなと思う。どうだろう？

**Comment by lmiller1990** [comment]
Actually yes, this should be a priority. I see two common cases:

1. testing Vue in apps that also use jquery (I think this is very common)
2. Testing Vue components that use other Vue libraries. The main libraries I see often are vee-validate, vuetify, and element-ui.

I have never written a test using both Vue and jquery, but it should be easy enough. https://jestjs.io/docs/en/tutorial-jquery

We should definitely talk about the common difficulties (Vue virtual dom and jquery conflict).
