### ISSUE TITLE
propsDataについて書きます

### ISSUE THREAD

**Issue by lmiller1990** [lmiller1990/vue-testing-handbook#4]
これに参考してください（英語）https://github.com/lmiller1990/vue-testing-handbook/issues/3

ここに書いてください。 https://github.com/lmiller1990/vue-testing-handbook/blob/master/docs/ja/components-with-props.md

テストコードも追加してください。`demo-app`。好きなようにコンポーネントなどを作ってもいいです。TDDで説明するととてもいいです。

**Comment by yk-hirao** [comment]
I will write this.

**Comment by yk-hirao** [comment]
this is correct link
https://github.com/lmiller1990/vue-testing-handbook/blob/master/src/ja/components-with-props.md

**Comment by lmiller1990** [comment]
ok, I think we should also talk about 
- [`setProps`](https://vue-test-utils.vuejs.org/api/wrapper/#setprops-props)
- ['props()`](https://vue-test-utils.vuejs.org/api/wrapper/#props)

**Comment by yk-hirao** [comment]
I think I should do two things from https://github.com/lmiller1990/vue-testing-handbook/issues/3

First, To write about `factory functions`
Second, how to use `propsData`

The first is almost finish writing, by @lmiller1990 at the file. Nice job :) So I will update docs a little.
The second, I thought I create `ColorButton.vue`, has two props, `text` and `color`. 

||required|default|
|:-:|:-:|:-:|
|text|TRUE|-|
|color|-|black|

The `text` props is required, so it created by `factory functions`.
But the `color` props is not required, so it created by propsData.

And Create the components by TDD.

How about this? @lmiller1990

**Comment by yk-hirao** [comment]
`ColorButton.vue` ってファイルだといい感じにファクトリ関数とpropsDataを渡すテストをかけそうな気がした！

**Comment by lmiller1990** [comment]
Sounds good. But I think the order should be the other way around. First, you write two tests. It will look something like this:

```
it("something", () => { 
  const wrapper = shallowMount(Foo, {
    propsData: {
     text: ...
      color: ... 
  })

  expect...
})

it("something else", () => { 
  const wrapper = shallowMount(Foo, {
    propsData: {
     text: ...
      color: ... 
  })

  expect...
})
```

Once the user sees the that we have to write the same thing twice, the benefit of a factory function will be more obvious. Talk about what a factory function is (a factory function is a function that returns a object), and show how we can use it to make our test more DRY:

```
function fooFactory(propsData) {
  return shallowMount(Foo, { 
    propData: { 
      color: ...
      ...propsData
    }
  }
}
```

now our test is like this

```
it(something...
  const wrapper = factory({ text: 'whatever text' })
```

**Comment by lmiller1990** [comment]
1. write component/test
2. tests are passing
3. explain factory function
4. implement factory
5. tests are still passing!

**Comment by lmiller1990** [comment]
Also I like the table to show the props + required/default. Great!

Maybe the next step is a PR (WIP is fine).

**Comment by yk-hirao** [comment]
@lmiller1990 
Thank you your comment :) I will!!
