### ISSUE TITLE
(ja) Unit test nearly e2e test

### ISSUE THREAD

**Issue by yk-hirao** [lmiller1990/vue-testing-handbook#41]
Please see this youtube

https://www.youtube.com/watch?v=OIpfWTThrK8&feature=youtu.be&t=7m47s

```js
import Parent from "Parent.vue"
import Child from "Child.vue"

const ChildInstance = wrapper.find(Child)
Child.vm.$emit("submitted")

expect(parentMethodMock).toBeCalled()
// Child.vm.$options.methods.submitted.call(Child.vm)
```

子コンポーネントから$emitを呼び出して親コンポーネントのメソッドが発火されるかどうかのテストができる。

Unitテストというよりe2eテストに近くなっていますが、こんな書き方もあるのでこれについて記事を書く。

**Comment by lmiller1990** [comment]
There is not much information about this, even in English. I think this would be a great guide to add. Would you like to work on it? I can translate it to English.
