### ISSUE TITLE
vue-testing-handbook用　OGP用画像/favicon

### ISSUE THREAD

**Issue by pinball1973b** [lmiller1990/vue-testing-handbook#44]
https://vuepress.vuejs.org/config/#head

いい感じのogp画像を作って設定する。

**Comment by ykhirao** [comment]
Why don't you make a favicon at the same time as solving this problem.

**Comment by ykhirao** [comment]
@pinball1973b Nice job :+1:

**Comment by lmiller1990** [comment]
for some reason the og:image is not showing, I am not sure why.

It should show here, right?

![image](https://user-images.githubusercontent.com/19196536/45014616-263edf80-b05a-11e8-8a1d-2777d216ed0a.png)

**Comment by lmiller1990** [comment]
Oh - I see the problem. `<meta name="...">` should be `<meta property="og:image">.

The spec is [here](http://ogp.me/#metadata). Someone should make a PR!

**Comment by t-niiru** [comment]
@lmiller1990 is this done?

![2018-11-23 14 01 51](https://user-images.githubusercontent.com/16680405/48929052-5ba3ec80-ef28-11e8-8cfc-d9953259fb03.png)

**Comment by lmiller1990** [comment]
It sure is!

![image](https://user-images.githubusercontent.com/19196536/48934991-c7e71600-ef51-11e8-9671-b97b68621006.png)

Closing.
