### ISSUE TITLE
Code example repeat typo

### ISSUE THREAD

**Issue by mr-africa** [lmiller1990/vue-testing-handbook#50]
Hello!
Thanks for great guide!
I'm found a typo here:
https://lmiller1990.github.io/vue-testing-handbook/vuex-in-components-mutations-and-actions.html#testing-with-a-real-vuex-store

In the code you repeat twice these lines:

```javascript
const localVue = createLocalVue()
localVue.use(Vuex)
```

**Comment by lmiller1990** [comment]
Hey @mr-africa , thanks for finding this. A full proofread is definitely in order at some point... would you like to make a PR fixing it? If so, feel free to. It'd be great to grow the contributors.

If you found any particular section useful or want more information, feel free to make an issue. Thanks!

**Comment by mr-africa** [comment]
I'm fix it #54

**Comment by lmiller1990** [comment]
Thanks, merged.

**Comment by mr-africa** [comment]
Thanks, don't forget to update github pages.
