### ISSUE TITLE
Guide on testing forms and inputs

### ISSUE THREAD

**Issue by lmiller1990** [lmiller1990/vue-testing-handbook#52]
There is a PR regarding this #37 in Japanese, but I think it's important to have it in English, too. We should have a guide about testing forms:

- how to use `setValue`, `setChecked` etc for radio buttons/checkboxes
- how to test select/option
- how to test forms in general (`find(Form).trigger('submit.prevent)` etc
- if the form is async (as most are) we need to use `flushPromises` and `await` maybe

etc.

**Comment by ProfessorTom** [comment]
Was the English guide ever produced?

**Comment by lmiller1990** [comment]
@ProfessorTom It was not - I started working on it but realized it's a huge topic, and since most people are using some kind of framework for their forms I didn't end up deciding what to include/not include (vuelidate, vee-validate, Vuetify...).

I'd be happy to write this (or accept a contribution) - any ideas or specific challenges you've encountered testing forms with Vue?

**Comment by lmiller1990** [comment]
We added this to the official docs, I think that's fine for now: https://vuejs.github.io/vue-test-utils-next-docs/guide/forms.html
