### ISSUE TITLE
Wrong implementation in "Simulating user input"

### ISSUE THREAD

**Issue by FrankySnow** [lmiller1990/vue-testing-handbook#93]
In the "Simulating user input" page, the test still passes even if the `submit` event is not triggered.

Using `v-show` on `div.message` only acts on the CSS, keeping the element in the DOM. You should use `v-if`.

``` html
    <div 
      class="message" 
      v-show="submitted" <!-- should be v-if -->
    >
```

The implementation in the demo-app repo is correct but this is not the one used in the docs.

**Comment by lmiller1990** [comment]
Woah, good catch. Will update this.

**Comment by FrankySnow** [comment]
I want to thank you for the handbook and this PR. I struggled a lot with this issue before finding the reason.

**Comment by lmiller1990** [comment]
No problem... if you have any ideas for guides I'm missing, just make an issue and we can get it added :)
