### ISSUE TITLE
How to fix doc?

### ISSUE THREAD

**Issue by Shinogasa** [lmiller1990/vue-testing-handbook#99]
Hi!

Thank you a good vue-testing-handbook!

I found typo in Japanese docs.
I want to fix it, but i don't know how to fix it.

Can i change html file direct? (ex:setting-up-for-tdd.html)
 Or other way?
(Is there a tool to make document?)

thanks！

---

こんにちは！
素敵なテキストをありがとうございます！

日本語のドキュメントにタイポを見つけました．
修正しようと思ったのですが修正の仕方がわかりませんでした．

これは直接htmlファイルを修正して大丈夫でしょうか？
それとも他の方法で修正するのでしょうか？
(ドキュメント生成のためのツールが有るとか)

よろしく！

**Comment by lmiller1990** [comment]
こんにちは @Shinogasa 。

1. repoをクローンします。`git clone https://.com/lmiller1990/vue-testing-handbook.git`

2. https://github.com/lmiller1990/vue-testing-handbook/tree/master/docs/jaの中にある`.md`ファイルを好きなように修正してください。`.html`を`vuepress`というツールで`.md`から生成するので修正しなくても大丈夫です。

3. ローカルで見たかったら、`yarn install`を実行して、`yarn dev`で実行してから`localhost:8080`に行きます。

PRをマージしてから、私の方で`yarn docs:build`を実行して、新しいバージョンをリリースします。

よろしくお願いします！

**Comment by Shinogasa** [comment]
ありがとうございます！
Thanks!!
